//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int id { get; set; }
        public string author { get; set; }
        public short year { get; set; }
        public string title { get; set; }
        public string table_contents { get; set; }
        public string description { get; set; }
    }
}
